#! /bin/sh
bspc monitor eDP -d 1 2 3 4 5 6 7 8 9 10 11 12
bspc monitor HDMI-A-0 -d 13 14

bspc config border_width        0
bspc config window_gap          1

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle       true
bspc config initial_polarity second_child
bspc config automatic_scheme longest_side

bspc config external_rules_command ~/.config/bspwm/bspwm-rules


# Multihead behavior
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

#sh ~/dotfiles/scripts/polybar_toggle.sh &
sh ~/.config/polybar/launch.sh &
sh ~/dotfiles/scripts/battery.sh &
dunst &
wmname LG3D
picom --config ~/.config/picom/picom.conf &
wal -i ~/dotfiles/background

# start other programms
thunderbird &

# lock the station
sh ~/dotfiles/scripts/lock.sh &

# source the colors.
. "${HOME}/.cache/wal/colors.sh"

# Set the border colors.
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_border_color "$color1"

bspc config presel_feedback_color "$color1"
