#!/bin/sh
#
# bspwm: external_rules_command

id=${1?};
instance=$3;
class=$2;

case $class in
 (Emacs) echo state=tiled\ layer=normal;;
 ([Ff]irefox|Firefox-esr|Iceweasel) echo desktop=1;;
 (Gimp*) echo follow=on;;
 (Gitk) echo state=floating\ layer=normal;;
 (Pavucontrol) echo desktop=3;;


 (Thunderbird) echo desktop=10;;
 (Spotify) echo desktop=9;;
 (TeamSpeak*) echo desktop=6;;
 ([sS]team*) echo desktop=7;;

 ([cC]hromium|Chromium-browser) echo desktop=2;;
 ([lL]ibre[oO]ffice*) echo state=tiled\ layer=normal;;
 (stj1) echo state=floating\ layer=above\ sticky=on;;
 ('')
  case $(ps -p "$(xdo pid $id)" -o comm= 2>/dev/null) in
   (spotify) echo desktop=9;;
  esac;;
esac;
