#! /bin/sh
bspc monitor LVDS1 -d 1 2 3 4 5 6 7 8
bspc monitor HDMI1 -d 9 10

bspc config border_width         0

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle       true
bspc config initial_polarity second_child
bspc config automatic_scheme longest_side

bspc rule -a Firefox desktop=^1
bspc rule -a TeamSpeak 3 desktop=^2
bspc rule -a Thunderbird desktop=^7
bspc rule -a keepassxc desktop=^8
bspc rule -a Steam desktop=^6
bspc rule -a LibreOffice* state=tiled

sh ~/.screenlayout/withoutTV.sh

sh ~/.config/polybar/launch.sh &
sh ~/.config/scripts/battery.sh &
gebaard -b
dunst &
setxkbmap de
xsetroot -cursor_name left_ptr
xrdb merge ~/.Xresources &
xbacklight -set 30
pactl set-sink-volume alsa_output.pci-0000_00_1b.0.analog-stereo 50%
pactl set-sink-mute alsa_output.pci-0000_00_1b.0.analog-stereo 1
wmname LG3D
compton --config ~/.config/compton/compton.conf &
wal -i ~/dotfiles/background
# start other programms
keepassxc &
thunderbird &

# lock the station
sh ~/.config/scripts/physlock.sh &

# source the colors.
. "${HOME}/.cache/wal/colors.sh"

# Set the border colors.
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_border_color "$color1"
