
[commands.swipe.three]
up = "rofi -modi drun -show drun -display-drun 'Programs: '"
down = "rofi -modi window -show window -display-window 'Workspace: '"
left = "bspc desktop -f prev"
right = "bspc desktop -f next"
